### ISSUE TITLE
OO Programmming

### ISSUE THREAD

**Issue by Phykick** [UncookedYogurt/PrimeNumbersAPI#1]
Unfortunately, Jesse doesn't seem to understand what this is. Look at his bunch of classes name d'MathmaticalMethods' or 'GraphicalMethods'. These are not objects. They will most likely consist of a load of static methods to be accesed from other classes.
You may as well be writing in python.

Suggestion: Maybe you want a class called 'Number' that represents, well, any number. Then inside that class you can have a bunch of methods which test certain things, e.g. is it prime. Then you might actually use that class as an object. (From there, another class, like PrimeNumber, could extend Number, and have a bunch more methods that you want to use when you know the int is prime, and you could cast between the two.)

**Comment by UncookedYogurt** [comment]
Wow....

Shot in the hearta

**Comment by Phykick** [comment]
> says can do java
> can't even do oo programming
