### ISSUE TITLE
Missing src/main/java and src/main/resources directories.

### ISSUE THREAD

**Issue by famzz** [UncookedYogurt/PrimeNumbersAPI#2]
The project is no longer a JavaFX project, therefore it is necessary to add the required directories as it is good convention.

**Comment by UncookedYogurt** [comment]
I understand, we need a source for all code; and the main code can is located in main. 
We can use multiple languages (potentially) so we need to delcare which code is located where i.e. Java code goes in Java
We also declare the resources for the main code, i.e. Databases

**Comment by UncookedYogurt** [comment]
I have created the new directories and put the items in them
